import { useState, useMemo, useEffect } from 'react'
import { Plus, X, Trash2, Link2, Check } from 'lucide-react'
import { Input, Button, SearchableSelect, Alert, toast } from '@/shared/components'
import { StepNavigation } from './StepNavigation'
import styles from './Steps.module.css'
import { useGoogleAdsWizardStore } from '../../stores/googleAdsWizardStore'
import { previewUtmString } from '../../utils/utmBuilder'
import type { Sitelink, Callout, StructuredSnippet } from '../../types/campaign'

export function StepExtensions() {
  const { extensions, setExtensionsData, markStepCompleted, campaign, adGroups, generatedFromArticle } = useGoogleAdsWizardStore()

  // Get the first ad group name for UTM building (sitelinks are campaign-level)
  const defaultAdGroupName = adGroups[0]?.name || 'grupo-anuncios'

  // Sitelink form state
  const [sitelinkForm, setSitelinkForm] = useState<Partial<Sitelink>>({
    text: '',
    description1: '',
    description2: '',
    finalUrl: '',
  })

  // Callout form state
  const [calloutText, setCalloutText] = useState('')

  // Structured snippet form state
  const [snippetHeader, setSnippetHeader] = useState('Servicos')
  const [snippetValues, setSnippetValues] = useState('')

  const handleAddSitelink = () => {
    if (!sitelinkForm.text || !sitelinkForm.finalUrl) return

    // Store base URL without UTMs - UTMs will be added at publish time
    const newSitelink: Sitelink = {
      id: `sitelink-${Date.now()}`,
      text: sitelinkForm.text!,
      description1: sitelinkForm.description1,
      description2: sitelinkForm.description2,
      finalUrl: sitelinkForm.finalUrl!, // Base URL only
    }

    setExtensionsData({
      sitelinks: [...extensions.sitelinks, newSitelink],
    })

    setSitelinkForm({ text: '', description1: '', description2: '', finalUrl: '' })
    markStepCompleted('extensions')
  }

  const handleRemoveSitelink = (id: string) => {
    setExtensionsData({
      sitelinks: extensions.sitelinks.filter(s => s.id !== id),
    })
  }

  const handleAddCallout = () => {
    if (!calloutText.trim()) return

    const newCallout: Callout = {
      id: `callout-${Date.now()}`,
      text: calloutText.slice(0, 25),
    }

    setExtensionsData({
      callouts: [...extensions.callouts, newCallout],
    })

    setCalloutText('')
    markStepCompleted('extensions')
  }

  const handleRemoveCallout = (id: string) => {
    setExtensionsData({
      callouts: extensions.callouts.filter(c => c.id !== id),
    })
  }

  const handleAddSnippet = () => {
    if (!snippetHeader || !snippetValues.trim()) return

    const values = snippetValues
      .split(',')
      .map(v => v.trim())
      .filter(v => v.length > 0)
      .slice(0, 10)

    if (values.length < 3) {
      toast.warning('Adicione pelo menos 3 valores')
      return
    }

    const newSnippet: StructuredSnippet = {
      id: `snippet-${Date.now()}`,
      header: snippetHeader,
      values,
    }

    setExtensionsData({
      structuredSnippets: [...extensions.structuredSnippets, newSnippet],
    })

    setSnippetValues('')
    markStepCompleted('extensions')
  }

  const handleRemoveSnippet = (id: string) => {
    setExtensionsData({
      structuredSnippets: extensions.structuredSnippets.filter(s => s.id !== id),
    })
  }

  const snippetHeaders = [
    'Servicos',
    'Marcas',
    'Tipos',
    'Estilos',
    'Modelos',
    'Destinos',
    'Cursos',
    'Amenidades',
    'Programas',
    'Cobertura de seguro',
  ]

  // Preview UTM string for sitelink
  const sitelinkUtmPreview = useMemo(() => {
    if (!sitelinkForm.finalUrl || !sitelinkForm.text) return ''
    return previewUtmString({
      campaignName: campaign.name,
      adGroupName: defaultAdGroupName,
      contentType: 'sitelink',
      contentName: sitelinkForm.text,
    })
  }, [campaign.name, defaultAdGroupName, sitelinkForm.finalUrl, sitelinkForm.text])

  // Check if extensions were auto-generated
  const hasAutoGeneratedExtensions = useMemo(() => {
    return generatedFromArticle?.extensions &&
      (generatedFromArticle.extensions.sitelinks?.length > 0 ||
       generatedFromArticle.extensions.callouts?.length > 0 ||
       generatedFromArticle.extensions.structuredSnippets?.length > 0)
  }, [generatedFromArticle])

  // Check if we have any extensions
  const hasExtensions = extensions.sitelinks.length > 0 ||
                        extensions.callouts.length > 0 ||
                        extensions.structuredSnippets.length > 0

  // Auto-mark step as completed if we have extensions
  useEffect(() => {
    if (hasExtensions) {
      markStepCompleted('extensions')
    }
  }, [hasExtensions, markStepCompleted])

  return (
    <div className={styles.stepContent}>
      {/* Success banner when extensions were auto-generated */}
      {hasAutoGeneratedExtensions && hasExtensions && (
        <Alert variant="success">
          <Check size={16} style={{ marginRight: '8px' }} />
          Extensões geradas automaticamente do artigo! Você pode editar ou adicionar mais extensões abaixo.
        </Alert>
      )}

      <section className={styles.section}>
        <h3 className={styles.sectionTitle}>Extensoes de Anuncio</h3>
        <p className={styles.sectionDescription}>
          Extensoes adicionam informacoes extras aos seus anuncios e aumentam a taxa de cliques.
          Elas sao gratuitas e altamente recomendadas.
        </p>
      </section>

      {/* Sitelinks */}
      <section className={styles.section}>
        <h3 className={styles.sectionTitle}>Sitelinks</h3>
        <p className={styles.sectionDescription}>
          Links adicionais que aparecem abaixo do seu anuncio direcionando para paginas especificas
        </p>

        {extensions.sitelinks.length > 0 && (
          <div className={styles.extensionsList}>
            {extensions.sitelinks.map((sitelink) => (
              <div key={sitelink.id} className={styles.extensionItem}>
                <div className={styles.extensionHeader}>
                  <span className={styles.extensionTitle}>{sitelink.text}</span>
                  <Button
                    variant="ghost"
                    size="sm"
                    leftIcon={<Trash2 size={14} />}
                    onClick={() => handleRemoveSitelink(sitelink.id)}
                  />
                </div>
                <p className={styles.hint}>{sitelink.finalUrl}</p>
              </div>
            ))}
          </div>
        )}

        <div className={styles.sitelinkForm}>
          <div className={styles.formGroup}>
            <Input
              label="Texto do link *"
              value={sitelinkForm.text || ''}
              onChange={(e) => setSitelinkForm({ ...sitelinkForm, text: e.target.value.slice(0, 25) })}
              placeholder="Ex: Fale Conosco"
              maxLength={25}
            />
            <span className={styles.hint}>{(sitelinkForm.text?.length || 0)}/25</span>
          </div>

          <div className={styles.formGroup}>
            <Input
              label="URL de destino *"
              value={sitelinkForm.finalUrl || ''}
              onChange={(e) => setSitelinkForm({ ...sitelinkForm, finalUrl: e.target.value })}
              placeholder="https://seusite.com.br/contato"
            />
            {sitelinkUtmPreview && (
              <div className={styles.utmPreview}>
                <Link2 size={12} />
                <span className={styles.utmPreviewLabel}>UTMs automaticos:</span>
                <code className={styles.utmPreviewCode}>{sitelinkUtmPreview}</code>
              </div>
            )}
          </div>

          <div className={styles.formGroup}>
            <Input
              label="Descricao linha 1 (opcional)"
              value={sitelinkForm.description1 || ''}
              onChange={(e) => setSitelinkForm({ ...sitelinkForm, description1: e.target.value.slice(0, 35) })}
              placeholder="Ex: Tire suas duvidas"
              maxLength={35}
            />
            <span className={styles.hint}>{(sitelinkForm.description1?.length || 0)}/35</span>
          </div>

          <div className={styles.formGroup}>
            <Input
              label="Descricao linha 2 (opcional)"
              value={sitelinkForm.description2 || ''}
              onChange={(e) => setSitelinkForm({ ...sitelinkForm, description2: e.target.value.slice(0, 35) })}
              placeholder="Ex: Resposta em 24h"
              maxLength={35}
            />
            <span className={styles.hint}>{(sitelinkForm.description2?.length || 0)}/35</span>
          </div>

          <Button
            variant="outline"
            leftIcon={<Plus size={14} />}
            onClick={handleAddSitelink}
            disabled={!sitelinkForm.text || !sitelinkForm.finalUrl}
            className={styles.fullWidth}
          >
            Adicionar sitelink
          </Button>
        </div>
      </section>

      {/* Callouts */}
      <section className={styles.section}>
        <h3 className={styles.sectionTitle}>Frases de Destaque</h3>
        <p className={styles.sectionDescription}>
          Textos curtos que destacam beneficios ou caracteristicas do seu negocio
        </p>

        {extensions.callouts.length > 0 && (
          <div className={styles.keywordsList}>
            {extensions.callouts.map((callout) => (
              <span key={callout.id} className={styles.keywordTag}>
                {callout.text}
                <button
                  type="button"
                  className={styles.keywordRemove}
                  onClick={() => handleRemoveCallout(callout.id)}
                >
                  <X size={12} />
                </button>
              </span>
            ))}
          </div>
        )}

        <div className={styles.inputWithButton}>
          <Input
            value={calloutText}
            onChange={(e) => setCalloutText(e.target.value.slice(0, 25))}
            placeholder="Ex: Frete gratis"
            maxLength={25}
          />
          <Button
            variant="outline"
            leftIcon={<Plus size={14} />}
            onClick={handleAddCallout}
            disabled={!calloutText.trim()}
          >
            Adicionar
          </Button>
        </div>
        <p className={styles.hint}>
          Sugestoes: Frete gratis | Atendimento 24h | Garantia de 30 dias | Parcele em 12x | Entrega rapida
        </p>
      </section>

      {/* Structured Snippets */}
      <section className={styles.section}>
        <h3 className={styles.sectionTitle}>Snippets Estruturados</h3>
        <p className={styles.sectionDescription}>
          Liste aspectos especificos dos seus produtos ou servicos
        </p>

        {extensions.structuredSnippets.length > 0 && (
          <div className={styles.extensionsList}>
            {extensions.structuredSnippets.map((snippet) => (
              <div key={snippet.id} className={styles.extensionItem}>
                <div className={styles.extensionHeader}>
                  <span className={styles.extensionTitle}>{snippet.header}</span>
                  <Button
                    variant="ghost"
                    size="sm"
                    leftIcon={<Trash2 size={14} />}
                    onClick={() => handleRemoveSnippet(snippet.id)}
                  />
                </div>
                <p className={styles.hint}>{snippet.values.join(', ')}</p>
              </div>
            ))}
          </div>
        )}

        <div className={styles.formGroup}>
          <SearchableSelect
            label="Cabecalho"
            options={snippetHeaders.map((header) => ({ value: header, label: header }))}
            value={snippetHeader}
            onChange={(value) => setSnippetHeader(value)}
            placeholder="Selecione o tipo..."
            fullWidth
          />
        </div>

        <div className={styles.formGroup}>
          <Input
            label="Valores (separados por virgula)"
            value={snippetValues}
            onChange={(e) => setSnippetValues(e.target.value)}
            placeholder="Ex: Consultoria, Treinamento, Suporte, Desenvolvimento"
          />
          <p className={styles.hint}>Minimo 3 valores, maximo 10</p>
        </div>

        <Button
          variant="outline"
          leftIcon={<Plus size={14} />}
          onClick={handleAddSnippet}
          disabled={!snippetValues.trim()}
        >
          Adicionar snippet
        </Button>
      </section>

      {/* Step Navigation */}
      <StepNavigation />
    </div>
  )
}
