/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIdRouteRouteImport } from './routes/workspace/$id/route'
import { Route as WorkspaceIdIndexRouteImport } from './routes/workspace/$id/index'
import { Route as WorkspaceIdTemplatesRouteImport } from './routes/workspace/$id/templates'
import { Route as WorkspaceIdSettingsRouteImport } from './routes/workspace/$id/settings'
import { Route as WorkspaceIdProfileRouteImport } from './routes/workspace/$id/profile'
import { Route as WorkspaceIdAiUsageRouteImport } from './routes/workspace/$id/ai-usage'
import { Route as WorkspaceIdProjectProjectIdRouteRouteImport } from './routes/workspace/$id/project/$projectId/route'
import { Route as WorkspaceIdProjectProjectIdIndexRouteImport } from './routes/workspace/$id/project/$projectId/index'
import { Route as WorkspaceIdProjectProjectIdWorkflowsIndexRouteImport } from './routes/workspace/$id/project/$projectId/workflows/index'
import { Route as WorkspaceIdProjectProjectIdStudioIndexRouteImport } from './routes/workspace/$id/project/$projectId/studio/index'
import { Route as WorkspaceIdProjectProjectIdSettingsIndexRouteImport } from './routes/workspace/$id/project/$projectId/settings/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRouteRoute = WorkspaceIdRouteRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdIndexRoute = WorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdTemplatesRoute = WorkspaceIdTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdSettingsRoute = WorkspaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdProfileRoute = WorkspaceIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdAiUsageRoute = WorkspaceIdAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdProjectProjectIdRouteRoute =
  WorkspaceIdProjectProjectIdRouteRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdIndexRoute =
  WorkspaceIdProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdWorkflowsIndexRoute =
  WorkspaceIdProjectProjectIdWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdStudioIndexRoute =
  WorkspaceIdProjectProjectIdStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdSettingsIndexRoute =
  WorkspaceIdProjectProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace/$id': typeof WorkspaceIdRouteRouteWithChildren
  '/workspace/$id/ai-usage': typeof WorkspaceIdAiUsageRoute
  '/workspace/$id/profile': typeof WorkspaceIdProfileRoute
  '/workspace/$id/settings': typeof WorkspaceIdSettingsRoute
  '/workspace/$id/templates': typeof WorkspaceIdTemplatesRoute
  '/workspace/$id/': typeof WorkspaceIdIndexRoute
  '/workspace/$id/project/$projectId': typeof WorkspaceIdProjectProjectIdRouteRouteWithChildren
  '/workspace/$id/project/$projectId/': typeof WorkspaceIdProjectProjectIdIndexRoute
  '/workspace/$id/project/$projectId/settings/': typeof WorkspaceIdProjectProjectIdSettingsIndexRoute
  '/workspace/$id/project/$projectId/studio/': typeof WorkspaceIdProjectProjectIdStudioIndexRoute
  '/workspace/$id/project/$projectId/workflows/': typeof WorkspaceIdProjectProjectIdWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace/$id/ai-usage': typeof WorkspaceIdAiUsageRoute
  '/workspace/$id/profile': typeof WorkspaceIdProfileRoute
  '/workspace/$id/settings': typeof WorkspaceIdSettingsRoute
  '/workspace/$id/templates': typeof WorkspaceIdTemplatesRoute
  '/workspace/$id': typeof WorkspaceIdIndexRoute
  '/workspace/$id/project/$projectId': typeof WorkspaceIdProjectProjectIdIndexRoute
  '/workspace/$id/project/$projectId/settings': typeof WorkspaceIdProjectProjectIdSettingsIndexRoute
  '/workspace/$id/project/$projectId/studio': typeof WorkspaceIdProjectProjectIdStudioIndexRoute
  '/workspace/$id/project/$projectId/workflows': typeof WorkspaceIdProjectProjectIdWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace/$id': typeof WorkspaceIdRouteRouteWithChildren
  '/workspace/$id/ai-usage': typeof WorkspaceIdAiUsageRoute
  '/workspace/$id/profile': typeof WorkspaceIdProfileRoute
  '/workspace/$id/settings': typeof WorkspaceIdSettingsRoute
  '/workspace/$id/templates': typeof WorkspaceIdTemplatesRoute
  '/workspace/$id/': typeof WorkspaceIdIndexRoute
  '/workspace/$id/project/$projectId': typeof WorkspaceIdProjectProjectIdRouteRouteWithChildren
  '/workspace/$id/project/$projectId/': typeof WorkspaceIdProjectProjectIdIndexRoute
  '/workspace/$id/project/$projectId/settings/': typeof WorkspaceIdProjectProjectIdSettingsIndexRoute
  '/workspace/$id/project/$projectId/studio/': typeof WorkspaceIdProjectProjectIdStudioIndexRoute
  '/workspace/$id/project/$projectId/workflows/': typeof WorkspaceIdProjectProjectIdWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace/$id'
    | '/workspace/$id/ai-usage'
    | '/workspace/$id/profile'
    | '/workspace/$id/settings'
    | '/workspace/$id/templates'
    | '/workspace/$id/'
    | '/workspace/$id/project/$projectId'
    | '/workspace/$id/project/$projectId/'
    | '/workspace/$id/project/$projectId/settings/'
    | '/workspace/$id/project/$projectId/studio/'
    | '/workspace/$id/project/$projectId/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace/$id/ai-usage'
    | '/workspace/$id/profile'
    | '/workspace/$id/settings'
    | '/workspace/$id/templates'
    | '/workspace/$id'
    | '/workspace/$id/project/$projectId'
    | '/workspace/$id/project/$projectId/settings'
    | '/workspace/$id/project/$projectId/studio'
    | '/workspace/$id/project/$projectId/workflows'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/workspace/$id'
    | '/workspace/$id/ai-usage'
    | '/workspace/$id/profile'
    | '/workspace/$id/settings'
    | '/workspace/$id/templates'
    | '/workspace/$id/'
    | '/workspace/$id/project/$projectId'
    | '/workspace/$id/project/$projectId/'
    | '/workspace/$id/project/$projectId/settings/'
    | '/workspace/$id/project/$projectId/studio/'
    | '/workspace/$id/project/$projectId/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WorkspaceIdRouteRoute: typeof WorkspaceIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id/': {
      id: '/workspace/$id/'
      path: '/'
      fullPath: '/workspace/$id/'
      preLoaderRoute: typeof WorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/templates': {
      id: '/workspace/$id/templates'
      path: '/templates'
      fullPath: '/workspace/$id/templates'
      preLoaderRoute: typeof WorkspaceIdTemplatesRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/settings': {
      id: '/workspace/$id/settings'
      path: '/settings'
      fullPath: '/workspace/$id/settings'
      preLoaderRoute: typeof WorkspaceIdSettingsRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/profile': {
      id: '/workspace/$id/profile'
      path: '/profile'
      fullPath: '/workspace/$id/profile'
      preLoaderRoute: typeof WorkspaceIdProfileRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/ai-usage': {
      id: '/workspace/$id/ai-usage'
      path: '/ai-usage'
      fullPath: '/workspace/$id/ai-usage'
      preLoaderRoute: typeof WorkspaceIdAiUsageRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/project/$projectId': {
      id: '/workspace/$id/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/workspace/$id/project/$projectId'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdRouteRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/project/$projectId/': {
      id: '/workspace/$id/project/$projectId/'
      path: '/'
      fullPath: '/workspace/$id/project/$projectId/'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdIndexRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
    '/workspace/$id/project/$projectId/workflows/': {
      id: '/workspace/$id/project/$projectId/workflows/'
      path: '/workflows'
      fullPath: '/workspace/$id/project/$projectId/workflows/'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdWorkflowsIndexRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
    '/workspace/$id/project/$projectId/studio/': {
      id: '/workspace/$id/project/$projectId/studio/'
      path: '/studio'
      fullPath: '/workspace/$id/project/$projectId/studio/'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdStudioIndexRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
    '/workspace/$id/project/$projectId/settings/': {
      id: '/workspace/$id/project/$projectId/settings/'
      path: '/settings'
      fullPath: '/workspace/$id/project/$projectId/settings/'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdSettingsIndexRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
  }
}

interface WorkspaceIdProjectProjectIdRouteRouteChildren {
  WorkspaceIdProjectProjectIdIndexRoute: typeof WorkspaceIdProjectProjectIdIndexRoute
  WorkspaceIdProjectProjectIdSettingsIndexRoute: typeof WorkspaceIdProjectProjectIdSettingsIndexRoute
  WorkspaceIdProjectProjectIdStudioIndexRoute: typeof WorkspaceIdProjectProjectIdStudioIndexRoute
  WorkspaceIdProjectProjectIdWorkflowsIndexRoute: typeof WorkspaceIdProjectProjectIdWorkflowsIndexRoute
}

const WorkspaceIdProjectProjectIdRouteRouteChildren: WorkspaceIdProjectProjectIdRouteRouteChildren =
  {
    WorkspaceIdProjectProjectIdIndexRoute:
      WorkspaceIdProjectProjectIdIndexRoute,
    WorkspaceIdProjectProjectIdSettingsIndexRoute:
      WorkspaceIdProjectProjectIdSettingsIndexRoute,
    WorkspaceIdProjectProjectIdStudioIndexRoute:
      WorkspaceIdProjectProjectIdStudioIndexRoute,
    WorkspaceIdProjectProjectIdWorkflowsIndexRoute:
      WorkspaceIdProjectProjectIdWorkflowsIndexRoute,
  }

const WorkspaceIdProjectProjectIdRouteRouteWithChildren =
  WorkspaceIdProjectProjectIdRouteRoute._addFileChildren(
    WorkspaceIdProjectProjectIdRouteRouteChildren,
  )

interface WorkspaceIdRouteRouteChildren {
  WorkspaceIdAiUsageRoute: typeof WorkspaceIdAiUsageRoute
  WorkspaceIdProfileRoute: typeof WorkspaceIdProfileRoute
  WorkspaceIdSettingsRoute: typeof WorkspaceIdSettingsRoute
  WorkspaceIdTemplatesRoute: typeof WorkspaceIdTemplatesRoute
  WorkspaceIdIndexRoute: typeof WorkspaceIdIndexRoute
  WorkspaceIdProjectProjectIdRouteRoute: typeof WorkspaceIdProjectProjectIdRouteRouteWithChildren
}

const WorkspaceIdRouteRouteChildren: WorkspaceIdRouteRouteChildren = {
  WorkspaceIdAiUsageRoute: WorkspaceIdAiUsageRoute,
  WorkspaceIdProfileRoute: WorkspaceIdProfileRoute,
  WorkspaceIdSettingsRoute: WorkspaceIdSettingsRoute,
  WorkspaceIdTemplatesRoute: WorkspaceIdTemplatesRoute,
  WorkspaceIdIndexRoute: WorkspaceIdIndexRoute,
  WorkspaceIdProjectProjectIdRouteRoute:
    WorkspaceIdProjectProjectIdRouteRouteWithChildren,
}

const WorkspaceIdRouteRouteWithChildren =
  WorkspaceIdRouteRoute._addFileChildren(WorkspaceIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WorkspaceIdRouteRoute: WorkspaceIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
