/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIdRouteRouteImport } from './routes/workspace/$id/route'
import { Route as WorkspaceIdIndexRouteImport } from './routes/workspace/$id/index'
import { Route as SharedTokenIndexRouteImport } from './routes/shared/$token/index'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth/callback/index'
import { Route as WorkspaceIdTemplatesRouteImport } from './routes/workspace/$id/templates'
import { Route as WorkspaceIdSettingsRouteImport } from './routes/workspace/$id/settings'
import { Route as WorkspaceIdProfileRouteImport } from './routes/workspace/$id/profile'
import { Route as WorkspaceIdAiUsageRouteImport } from './routes/workspace/$id/ai-usage'
import { Route as WorkspaceIdWorkflowsIndexRouteImport } from './routes/workspace/$id/workflows/index'
import { Route as WorkspaceIdWorkflowsTemplatesRouteImport } from './routes/workspace/$id/workflows/templates'
import { Route as WorkspaceIdProjectProjectIdRouteRouteImport } from './routes/workspace/$id/project/$projectId/route'
import { Route as WorkspaceIdProjectProjectIdIndexRouteImport } from './routes/workspace/$id/project/$projectId/index'
import { Route as WorkspaceIdWorkflowsExecutionsExecutionIdIndexRouteImport } from './routes/workspace/$id/workflows/executions/$executionId/index'
import { Route as WorkspaceIdProjectProjectIdWorkflowsIndexRouteImport } from './routes/workspace/$id/project/$projectId/workflows/index'
import { Route as WorkspaceIdProjectProjectIdStudioIndexRouteImport } from './routes/workspace/$id/project/$projectId/studio/index'
import { Route as WorkspaceIdProjectProjectIdSettingsIndexRouteImport } from './routes/workspace/$id/project/$projectId/settings/index'
import { Route as WorkspaceIdProjectProjectIdWorkflowsNewRouteImport } from './routes/workspace/$id/project/$projectId/workflows/new'
import { Route as WorkspaceIdProjectProjectIdSettingsVisualContextRouteImport } from './routes/workspace/$id/project/$projectId/settings/visual-context'
import { Route as WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRouteImport } from './routes/workspace/$id/project/$projectId/workflows/$workflowId/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRouteRoute = WorkspaceIdRouteRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdIndexRoute = WorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const SharedTokenIndexRoute = SharedTokenIndexRouteImport.update({
  id: '/shared/$token/',
  path: '/shared/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdTemplatesRoute = WorkspaceIdTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdSettingsRoute = WorkspaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdProfileRoute = WorkspaceIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdAiUsageRoute = WorkspaceIdAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => WorkspaceIdRouteRoute,
} as any)
const WorkspaceIdWorkflowsIndexRoute =
  WorkspaceIdWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const WorkspaceIdWorkflowsTemplatesRoute =
  WorkspaceIdWorkflowsTemplatesRouteImport.update({
    id: '/workflows/templates',
    path: '/workflows/templates',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdRouteRoute =
  WorkspaceIdProjectProjectIdRouteRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdIndexRoute =
  WorkspaceIdProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)
const WorkspaceIdWorkflowsExecutionsExecutionIdIndexRoute =
  WorkspaceIdWorkflowsExecutionsExecutionIdIndexRouteImport.update({
    id: '/workflows/executions/$executionId/',
    path: '/workflows/executions/$executionId/',
    getParentRoute: () => WorkspaceIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdWorkflowsIndexRoute =
  WorkspaceIdProjectProjectIdWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdStudioIndexRoute =
  WorkspaceIdProjectProjectIdStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdSettingsIndexRoute =
  WorkspaceIdProjectProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdWorkflowsNewRoute =
  WorkspaceIdProjectProjectIdWorkflowsNewRouteImport.update({
    id: '/workflows/new',
    path: '/workflows/new',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdSettingsVisualContextRoute =
  WorkspaceIdProjectProjectIdSettingsVisualContextRouteImport.update({
    id: '/settings/visual-context',
    path: '/settings/visual-context',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)
const WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRoute =
  WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRouteImport.update({
    id: '/workflows/$workflowId/',
    path: '/workflows/$workflowId/',
    getParentRoute: () => WorkspaceIdProjectProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace/$id': typeof WorkspaceIdRouteRouteWithChildren
  '/workspace/$id/ai-usage': typeof WorkspaceIdAiUsageRoute
  '/workspace/$id/profile': typeof WorkspaceIdProfileRoute
  '/workspace/$id/settings': typeof WorkspaceIdSettingsRoute
  '/workspace/$id/templates': typeof WorkspaceIdTemplatesRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/shared/$token/': typeof SharedTokenIndexRoute
  '/workspace/$id/': typeof WorkspaceIdIndexRoute
  '/workspace/$id/project/$projectId': typeof WorkspaceIdProjectProjectIdRouteRouteWithChildren
  '/workspace/$id/workflows/templates': typeof WorkspaceIdWorkflowsTemplatesRoute
  '/workspace/$id/workflows/': typeof WorkspaceIdWorkflowsIndexRoute
  '/workspace/$id/project/$projectId/': typeof WorkspaceIdProjectProjectIdIndexRoute
  '/workspace/$id/project/$projectId/settings/visual-context': typeof WorkspaceIdProjectProjectIdSettingsVisualContextRoute
  '/workspace/$id/project/$projectId/workflows/new': typeof WorkspaceIdProjectProjectIdWorkflowsNewRoute
  '/workspace/$id/project/$projectId/settings/': typeof WorkspaceIdProjectProjectIdSettingsIndexRoute
  '/workspace/$id/project/$projectId/studio/': typeof WorkspaceIdProjectProjectIdStudioIndexRoute
  '/workspace/$id/project/$projectId/workflows/': typeof WorkspaceIdProjectProjectIdWorkflowsIndexRoute
  '/workspace/$id/workflows/executions/$executionId/': typeof WorkspaceIdWorkflowsExecutionsExecutionIdIndexRoute
  '/workspace/$id/project/$projectId/workflows/$workflowId/': typeof WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace/$id/ai-usage': typeof WorkspaceIdAiUsageRoute
  '/workspace/$id/profile': typeof WorkspaceIdProfileRoute
  '/workspace/$id/settings': typeof WorkspaceIdSettingsRoute
  '/workspace/$id/templates': typeof WorkspaceIdTemplatesRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/shared/$token': typeof SharedTokenIndexRoute
  '/workspace/$id': typeof WorkspaceIdIndexRoute
  '/workspace/$id/workflows/templates': typeof WorkspaceIdWorkflowsTemplatesRoute
  '/workspace/$id/workflows': typeof WorkspaceIdWorkflowsIndexRoute
  '/workspace/$id/project/$projectId': typeof WorkspaceIdProjectProjectIdIndexRoute
  '/workspace/$id/project/$projectId/settings/visual-context': typeof WorkspaceIdProjectProjectIdSettingsVisualContextRoute
  '/workspace/$id/project/$projectId/workflows/new': typeof WorkspaceIdProjectProjectIdWorkflowsNewRoute
  '/workspace/$id/project/$projectId/settings': typeof WorkspaceIdProjectProjectIdSettingsIndexRoute
  '/workspace/$id/project/$projectId/studio': typeof WorkspaceIdProjectProjectIdStudioIndexRoute
  '/workspace/$id/project/$projectId/workflows': typeof WorkspaceIdProjectProjectIdWorkflowsIndexRoute
  '/workspace/$id/workflows/executions/$executionId': typeof WorkspaceIdWorkflowsExecutionsExecutionIdIndexRoute
  '/workspace/$id/project/$projectId/workflows/$workflowId': typeof WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace/$id': typeof WorkspaceIdRouteRouteWithChildren
  '/workspace/$id/ai-usage': typeof WorkspaceIdAiUsageRoute
  '/workspace/$id/profile': typeof WorkspaceIdProfileRoute
  '/workspace/$id/settings': typeof WorkspaceIdSettingsRoute
  '/workspace/$id/templates': typeof WorkspaceIdTemplatesRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/shared/$token/': typeof SharedTokenIndexRoute
  '/workspace/$id/': typeof WorkspaceIdIndexRoute
  '/workspace/$id/project/$projectId': typeof WorkspaceIdProjectProjectIdRouteRouteWithChildren
  '/workspace/$id/workflows/templates': typeof WorkspaceIdWorkflowsTemplatesRoute
  '/workspace/$id/workflows/': typeof WorkspaceIdWorkflowsIndexRoute
  '/workspace/$id/project/$projectId/': typeof WorkspaceIdProjectProjectIdIndexRoute
  '/workspace/$id/project/$projectId/settings/visual-context': typeof WorkspaceIdProjectProjectIdSettingsVisualContextRoute
  '/workspace/$id/project/$projectId/workflows/new': typeof WorkspaceIdProjectProjectIdWorkflowsNewRoute
  '/workspace/$id/project/$projectId/settings/': typeof WorkspaceIdProjectProjectIdSettingsIndexRoute
  '/workspace/$id/project/$projectId/studio/': typeof WorkspaceIdProjectProjectIdStudioIndexRoute
  '/workspace/$id/project/$projectId/workflows/': typeof WorkspaceIdProjectProjectIdWorkflowsIndexRoute
  '/workspace/$id/workflows/executions/$executionId/': typeof WorkspaceIdWorkflowsExecutionsExecutionIdIndexRoute
  '/workspace/$id/project/$projectId/workflows/$workflowId/': typeof WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace/$id'
    | '/workspace/$id/ai-usage'
    | '/workspace/$id/profile'
    | '/workspace/$id/settings'
    | '/workspace/$id/templates'
    | '/auth/callback/'
    | '/shared/$token/'
    | '/workspace/$id/'
    | '/workspace/$id/project/$projectId'
    | '/workspace/$id/workflows/templates'
    | '/workspace/$id/workflows/'
    | '/workspace/$id/project/$projectId/'
    | '/workspace/$id/project/$projectId/settings/visual-context'
    | '/workspace/$id/project/$projectId/workflows/new'
    | '/workspace/$id/project/$projectId/settings/'
    | '/workspace/$id/project/$projectId/studio/'
    | '/workspace/$id/project/$projectId/workflows/'
    | '/workspace/$id/workflows/executions/$executionId/'
    | '/workspace/$id/project/$projectId/workflows/$workflowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/workspace/$id/ai-usage'
    | '/workspace/$id/profile'
    | '/workspace/$id/settings'
    | '/workspace/$id/templates'
    | '/auth/callback'
    | '/shared/$token'
    | '/workspace/$id'
    | '/workspace/$id/workflows/templates'
    | '/workspace/$id/workflows'
    | '/workspace/$id/project/$projectId'
    | '/workspace/$id/project/$projectId/settings/visual-context'
    | '/workspace/$id/project/$projectId/workflows/new'
    | '/workspace/$id/project/$projectId/settings'
    | '/workspace/$id/project/$projectId/studio'
    | '/workspace/$id/project/$projectId/workflows'
    | '/workspace/$id/workflows/executions/$executionId'
    | '/workspace/$id/project/$projectId/workflows/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/workspace/$id'
    | '/workspace/$id/ai-usage'
    | '/workspace/$id/profile'
    | '/workspace/$id/settings'
    | '/workspace/$id/templates'
    | '/auth/callback/'
    | '/shared/$token/'
    | '/workspace/$id/'
    | '/workspace/$id/project/$projectId'
    | '/workspace/$id/workflows/templates'
    | '/workspace/$id/workflows/'
    | '/workspace/$id/project/$projectId/'
    | '/workspace/$id/project/$projectId/settings/visual-context'
    | '/workspace/$id/project/$projectId/workflows/new'
    | '/workspace/$id/project/$projectId/settings/'
    | '/workspace/$id/project/$projectId/studio/'
    | '/workspace/$id/project/$projectId/workflows/'
    | '/workspace/$id/workflows/executions/$executionId/'
    | '/workspace/$id/project/$projectId/workflows/$workflowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WorkspaceIdRouteRoute: typeof WorkspaceIdRouteRouteWithChildren
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
  SharedTokenIndexRoute: typeof SharedTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id/': {
      id: '/workspace/$id/'
      path: '/'
      fullPath: '/workspace/$id/'
      preLoaderRoute: typeof WorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/shared/$token/': {
      id: '/shared/$token/'
      path: '/shared/$token'
      fullPath: '/shared/$token/'
      preLoaderRoute: typeof SharedTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback/'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id/templates': {
      id: '/workspace/$id/templates'
      path: '/templates'
      fullPath: '/workspace/$id/templates'
      preLoaderRoute: typeof WorkspaceIdTemplatesRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/settings': {
      id: '/workspace/$id/settings'
      path: '/settings'
      fullPath: '/workspace/$id/settings'
      preLoaderRoute: typeof WorkspaceIdSettingsRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/profile': {
      id: '/workspace/$id/profile'
      path: '/profile'
      fullPath: '/workspace/$id/profile'
      preLoaderRoute: typeof WorkspaceIdProfileRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/ai-usage': {
      id: '/workspace/$id/ai-usage'
      path: '/ai-usage'
      fullPath: '/workspace/$id/ai-usage'
      preLoaderRoute: typeof WorkspaceIdAiUsageRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/workflows/': {
      id: '/workspace/$id/workflows/'
      path: '/workflows'
      fullPath: '/workspace/$id/workflows/'
      preLoaderRoute: typeof WorkspaceIdWorkflowsIndexRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/workflows/templates': {
      id: '/workspace/$id/workflows/templates'
      path: '/workflows/templates'
      fullPath: '/workspace/$id/workflows/templates'
      preLoaderRoute: typeof WorkspaceIdWorkflowsTemplatesRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/project/$projectId': {
      id: '/workspace/$id/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/workspace/$id/project/$projectId'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdRouteRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/project/$projectId/': {
      id: '/workspace/$id/project/$projectId/'
      path: '/'
      fullPath: '/workspace/$id/project/$projectId/'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdIndexRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
    '/workspace/$id/workflows/executions/$executionId/': {
      id: '/workspace/$id/workflows/executions/$executionId/'
      path: '/workflows/executions/$executionId'
      fullPath: '/workspace/$id/workflows/executions/$executionId/'
      preLoaderRoute: typeof WorkspaceIdWorkflowsExecutionsExecutionIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRouteRoute
    }
    '/workspace/$id/project/$projectId/workflows/': {
      id: '/workspace/$id/project/$projectId/workflows/'
      path: '/workflows'
      fullPath: '/workspace/$id/project/$projectId/workflows/'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdWorkflowsIndexRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
    '/workspace/$id/project/$projectId/studio/': {
      id: '/workspace/$id/project/$projectId/studio/'
      path: '/studio'
      fullPath: '/workspace/$id/project/$projectId/studio/'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdStudioIndexRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
    '/workspace/$id/project/$projectId/settings/': {
      id: '/workspace/$id/project/$projectId/settings/'
      path: '/settings'
      fullPath: '/workspace/$id/project/$projectId/settings/'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdSettingsIndexRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
    '/workspace/$id/project/$projectId/workflows/new': {
      id: '/workspace/$id/project/$projectId/workflows/new'
      path: '/workflows/new'
      fullPath: '/workspace/$id/project/$projectId/workflows/new'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdWorkflowsNewRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
    '/workspace/$id/project/$projectId/settings/visual-context': {
      id: '/workspace/$id/project/$projectId/settings/visual-context'
      path: '/settings/visual-context'
      fullPath: '/workspace/$id/project/$projectId/settings/visual-context'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdSettingsVisualContextRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
    '/workspace/$id/project/$projectId/workflows/$workflowId/': {
      id: '/workspace/$id/project/$projectId/workflows/$workflowId/'
      path: '/workflows/$workflowId'
      fullPath: '/workspace/$id/project/$projectId/workflows/$workflowId/'
      preLoaderRoute: typeof WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof WorkspaceIdProjectProjectIdRouteRoute
    }
  }
}

interface WorkspaceIdProjectProjectIdRouteRouteChildren {
  WorkspaceIdProjectProjectIdIndexRoute: typeof WorkspaceIdProjectProjectIdIndexRoute
  WorkspaceIdProjectProjectIdSettingsVisualContextRoute: typeof WorkspaceIdProjectProjectIdSettingsVisualContextRoute
  WorkspaceIdProjectProjectIdWorkflowsNewRoute: typeof WorkspaceIdProjectProjectIdWorkflowsNewRoute
  WorkspaceIdProjectProjectIdSettingsIndexRoute: typeof WorkspaceIdProjectProjectIdSettingsIndexRoute
  WorkspaceIdProjectProjectIdStudioIndexRoute: typeof WorkspaceIdProjectProjectIdStudioIndexRoute
  WorkspaceIdProjectProjectIdWorkflowsIndexRoute: typeof WorkspaceIdProjectProjectIdWorkflowsIndexRoute
  WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRoute: typeof WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRoute
}

const WorkspaceIdProjectProjectIdRouteRouteChildren: WorkspaceIdProjectProjectIdRouteRouteChildren =
  {
    WorkspaceIdProjectProjectIdIndexRoute:
      WorkspaceIdProjectProjectIdIndexRoute,
    WorkspaceIdProjectProjectIdSettingsVisualContextRoute:
      WorkspaceIdProjectProjectIdSettingsVisualContextRoute,
    WorkspaceIdProjectProjectIdWorkflowsNewRoute:
      WorkspaceIdProjectProjectIdWorkflowsNewRoute,
    WorkspaceIdProjectProjectIdSettingsIndexRoute:
      WorkspaceIdProjectProjectIdSettingsIndexRoute,
    WorkspaceIdProjectProjectIdStudioIndexRoute:
      WorkspaceIdProjectProjectIdStudioIndexRoute,
    WorkspaceIdProjectProjectIdWorkflowsIndexRoute:
      WorkspaceIdProjectProjectIdWorkflowsIndexRoute,
    WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRoute:
      WorkspaceIdProjectProjectIdWorkflowsWorkflowIdIndexRoute,
  }

const WorkspaceIdProjectProjectIdRouteRouteWithChildren =
  WorkspaceIdProjectProjectIdRouteRoute._addFileChildren(
    WorkspaceIdProjectProjectIdRouteRouteChildren,
  )

interface WorkspaceIdRouteRouteChildren {
  WorkspaceIdAiUsageRoute: typeof WorkspaceIdAiUsageRoute
  WorkspaceIdProfileRoute: typeof WorkspaceIdProfileRoute
  WorkspaceIdSettingsRoute: typeof WorkspaceIdSettingsRoute
  WorkspaceIdTemplatesRoute: typeof WorkspaceIdTemplatesRoute
  WorkspaceIdIndexRoute: typeof WorkspaceIdIndexRoute
  WorkspaceIdProjectProjectIdRouteRoute: typeof WorkspaceIdProjectProjectIdRouteRouteWithChildren
  WorkspaceIdWorkflowsTemplatesRoute: typeof WorkspaceIdWorkflowsTemplatesRoute
  WorkspaceIdWorkflowsIndexRoute: typeof WorkspaceIdWorkflowsIndexRoute
  WorkspaceIdWorkflowsExecutionsExecutionIdIndexRoute: typeof WorkspaceIdWorkflowsExecutionsExecutionIdIndexRoute
}

const WorkspaceIdRouteRouteChildren: WorkspaceIdRouteRouteChildren = {
  WorkspaceIdAiUsageRoute: WorkspaceIdAiUsageRoute,
  WorkspaceIdProfileRoute: WorkspaceIdProfileRoute,
  WorkspaceIdSettingsRoute: WorkspaceIdSettingsRoute,
  WorkspaceIdTemplatesRoute: WorkspaceIdTemplatesRoute,
  WorkspaceIdIndexRoute: WorkspaceIdIndexRoute,
  WorkspaceIdProjectProjectIdRouteRoute:
    WorkspaceIdProjectProjectIdRouteRouteWithChildren,
  WorkspaceIdWorkflowsTemplatesRoute: WorkspaceIdWorkflowsTemplatesRoute,
  WorkspaceIdWorkflowsIndexRoute: WorkspaceIdWorkflowsIndexRoute,
  WorkspaceIdWorkflowsExecutionsExecutionIdIndexRoute:
    WorkspaceIdWorkflowsExecutionsExecutionIdIndexRoute,
}

const WorkspaceIdRouteRouteWithChildren =
  WorkspaceIdRouteRoute._addFileChildren(WorkspaceIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WorkspaceIdRouteRoute: WorkspaceIdRouteRouteWithChildren,
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
  SharedTokenIndexRoute: SharedTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
