/**
 * Complete list of countries with ISO 3166-1 alpha-2 codes
 * Source: https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes
 *
 * This list is used as fallback when Meta API is unavailable
 * and ensures all countries are available for targeting.
 */
export const COUNTRIES = [
  { key: "AF", name: "Afghanistan", countryCode: "AF" },
  { key: "AX", name: "Åland Islands", countryCode: "AX" },
  { key: "AL", name: "Albania", countryCode: "AL" },
  { key: "DZ", name: "Algeria", countryCode: "DZ" },
  { key: "AS", name: "American Samoa", countryCode: "AS" },
  { key: "AD", name: "Andorra", countryCode: "AD" },
  { key: "AO", name: "Angola", countryCode: "AO" },
  { key: "AI", name: "Anguilla", countryCode: "AI" },
  { key: "AQ", name: "Antarctica", countryCode: "AQ" },
  { key: "AG", name: "Antigua and Barbuda", countryCode: "AG" },
  { key: "AR", name: "Argentina", countryCode: "AR" },
  { key: "AM", name: "Armenia", countryCode: "AM" },
  { key: "AW", name: "Aruba", countryCode: "AW" },
  { key: "AU", name: "Australia", countryCode: "AU" },
  { key: "AT", name: "Austria", countryCode: "AT" },
  { key: "AZ", name: "Azerbaijan", countryCode: "AZ" },
  { key: "BS", name: "Bahamas", countryCode: "BS" },
  { key: "BH", name: "Bahrain", countryCode: "BH" },
  { key: "BD", name: "Bangladesh", countryCode: "BD" },
  { key: "BB", name: "Barbados", countryCode: "BB" },
  { key: "BY", name: "Belarus", countryCode: "BY" },
  { key: "BE", name: "Belgium", countryCode: "BE" },
  { key: "BZ", name: "Belize", countryCode: "BZ" },
  { key: "BJ", name: "Benin", countryCode: "BJ" },
  { key: "BM", name: "Bermuda", countryCode: "BM" },
  { key: "BT", name: "Bhutan", countryCode: "BT" },
  { key: "BO", name: "Bolivia", countryCode: "BO" },
  { key: "BQ", name: "Bonaire, Sint Eustatius and Saba", countryCode: "BQ" },
  { key: "BA", name: "Bosnia and Herzegovina", countryCode: "BA" },
  { key: "BW", name: "Botswana", countryCode: "BW" },
  { key: "BV", name: "Bouvet Island", countryCode: "BV" },
  { key: "BR", name: "Brazil", countryCode: "BR" },
  { key: "IO", name: "British Indian Ocean Territory", countryCode: "IO" },
  { key: "BN", name: "Brunei Darussalam", countryCode: "BN" },
  { key: "BG", name: "Bulgaria", countryCode: "BG" },
  { key: "BF", name: "Burkina Faso", countryCode: "BF" },
  { key: "BI", name: "Burundi", countryCode: "BI" },
  { key: "CV", name: "Cabo Verde", countryCode: "CV" },
  { key: "KH", name: "Cambodia", countryCode: "KH" },
  { key: "CM", name: "Cameroon", countryCode: "CM" },
  { key: "CA", name: "Canada", countryCode: "CA" },
  { key: "KY", name: "Cayman Islands", countryCode: "KY" },
  { key: "CF", name: "Central African Republic", countryCode: "CF" },
  { key: "TD", name: "Chad", countryCode: "TD" },
  { key: "CL", name: "Chile", countryCode: "CL" },
  { key: "CN", name: "China", countryCode: "CN" },
  { key: "CX", name: "Christmas Island", countryCode: "CX" },
  { key: "CC", name: "Cocos (Keeling) Islands", countryCode: "CC" },
  { key: "CO", name: "Colombia", countryCode: "CO" },
  { key: "KM", name: "Comoros", countryCode: "KM" },
  { key: "CG", name: "Congo", countryCode: "CG" },
  { key: "CD", name: "Congo, Democratic Republic of the", countryCode: "CD" },
  { key: "CK", name: "Cook Islands", countryCode: "CK" },
  { key: "CR", name: "Costa Rica", countryCode: "CR" },
  { key: "CI", name: "Côte d'Ivoire", countryCode: "CI" },
  { key: "HR", name: "Croatia", countryCode: "HR" },
  { key: "CU", name: "Cuba", countryCode: "CU" },
  { key: "CW", name: "Curaçao", countryCode: "CW" },
  { key: "CY", name: "Cyprus", countryCode: "CY" },
  { key: "CZ", name: "Czechia", countryCode: "CZ" },
  { key: "DK", name: "Denmark", countryCode: "DK" },
  { key: "DJ", name: "Djibouti", countryCode: "DJ" },
  { key: "DM", name: "Dominica", countryCode: "DM" },
  { key: "DO", name: "Dominican Republic", countryCode: "DO" },
  { key: "EC", name: "Ecuador", countryCode: "EC" },
  { key: "EG", name: "Egypt", countryCode: "EG" },
  { key: "SV", name: "El Salvador", countryCode: "SV" },
  { key: "GQ", name: "Equatorial Guinea", countryCode: "GQ" },
  { key: "ER", name: "Eritrea", countryCode: "ER" },
  { key: "EE", name: "Estonia", countryCode: "EE" },
  { key: "SZ", name: "Eswatini", countryCode: "SZ" },
  { key: "ET", name: "Ethiopia", countryCode: "ET" },
  { key: "FK", name: "Falkland Islands (Malvinas)", countryCode: "FK" },
  { key: "FO", name: "Faroe Islands", countryCode: "FO" },
  { key: "FJ", name: "Fiji", countryCode: "FJ" },
  { key: "FI", name: "Finland", countryCode: "FI" },
  { key: "FR", name: "France", countryCode: "FR" },
  { key: "GF", name: "French Guiana", countryCode: "GF" },
  { key: "PF", name: "French Polynesia", countryCode: "PF" },
  { key: "TF", name: "French Southern Territories", countryCode: "TF" },
  { key: "GA", name: "Gabon", countryCode: "GA" },
  { key: "GM", name: "Gambia", countryCode: "GM" },
  { key: "GE", name: "Georgia", countryCode: "GE" },
  { key: "DE", name: "Germany", countryCode: "DE" },
  { key: "GH", name: "Ghana", countryCode: "GH" },
  { key: "GI", name: "Gibraltar", countryCode: "GI" },
  { key: "GR", name: "Greece", countryCode: "GR" },
  { key: "GL", name: "Greenland", countryCode: "GL" },
  { key: "GD", name: "Grenada", countryCode: "GD" },
  { key: "GP", name: "Guadeloupe", countryCode: "GP" },
  { key: "GU", name: "Guam", countryCode: "GU" },
  { key: "GT", name: "Guatemala", countryCode: "GT" },
  { key: "GG", name: "Guernsey", countryCode: "GG" },
  { key: "GN", name: "Guinea", countryCode: "GN" },
  { key: "GW", name: "Guinea-Bissau", countryCode: "GW" },
  { key: "GY", name: "Guyana", countryCode: "GY" },
  { key: "HT", name: "Haiti", countryCode: "HT" },
  { key: "HM", name: "Heard Island and McDonald Islands", countryCode: "HM" },
  { key: "VA", name: "Holy See", countryCode: "VA" },
  { key: "HN", name: "Honduras", countryCode: "HN" },
  { key: "HK", name: "Hong Kong", countryCode: "HK" },
  { key: "HU", name: "Hungary", countryCode: "HU" },
  { key: "IS", name: "Iceland", countryCode: "IS" },
  { key: "IN", name: "India", countryCode: "IN" },
  { key: "ID", name: "Indonesia", countryCode: "ID" },
  { key: "IR", name: "Iran", countryCode: "IR" },
  { key: "IQ", name: "Iraq", countryCode: "IQ" },
  { key: "IE", name: "Ireland", countryCode: "IE" },
  { key: "IM", name: "Isle of Man", countryCode: "IM" },
  { key: "IL", name: "Israel", countryCode: "IL" },
  { key: "IT", name: "Italy", countryCode: "IT" },
  { key: "JM", name: "Jamaica", countryCode: "JM" },
  { key: "JP", name: "Japan", countryCode: "JP" },
  { key: "JE", name: "Jersey", countryCode: "JE" },
  { key: "JO", name: "Jordan", countryCode: "JO" },
  { key: "KZ", name: "Kazakhstan", countryCode: "KZ" },
  { key: "KE", name: "Kenya", countryCode: "KE" },
  { key: "KI", name: "Kiribati", countryCode: "KI" },
  { key: "KP", name: "Korea, North", countryCode: "KP" },
  { key: "KR", name: "Korea, South", countryCode: "KR" },
  { key: "KW", name: "Kuwait", countryCode: "KW" },
  { key: "KG", name: "Kyrgyzstan", countryCode: "KG" },
  { key: "LA", name: "Laos", countryCode: "LA" },
  { key: "LV", name: "Latvia", countryCode: "LV" },
  { key: "LB", name: "Lebanon", countryCode: "LB" },
  { key: "LS", name: "Lesotho", countryCode: "LS" },
  { key: "LR", name: "Liberia", countryCode: "LR" },
  { key: "LY", name: "Libya", countryCode: "LY" },
  { key: "LI", name: "Liechtenstein", countryCode: "LI" },
  { key: "LT", name: "Lithuania", countryCode: "LT" },
  { key: "LU", name: "Luxembourg", countryCode: "LU" },
  { key: "MO", name: "Macao", countryCode: "MO" },
  { key: "MG", name: "Madagascar", countryCode: "MG" },
  { key: "MW", name: "Malawi", countryCode: "MW" },
  { key: "MY", name: "Malaysia", countryCode: "MY" },
  { key: "MV", name: "Maldives", countryCode: "MV" },
  { key: "ML", name: "Mali", countryCode: "ML" },
  { key: "MT", name: "Malta", countryCode: "MT" },
  { key: "MH", name: "Marshall Islands", countryCode: "MH" },
  { key: "MQ", name: "Martinique", countryCode: "MQ" },
  { key: "MR", name: "Mauritania", countryCode: "MR" },
  { key: "MU", name: "Mauritius", countryCode: "MU" },
  { key: "YT", name: "Mayotte", countryCode: "YT" },
  { key: "MX", name: "Mexico", countryCode: "MX" },
  { key: "FM", name: "Micronesia", countryCode: "FM" },
  { key: "MD", name: "Moldova", countryCode: "MD" },
  { key: "MC", name: "Monaco", countryCode: "MC" },
  { key: "MN", name: "Mongolia", countryCode: "MN" },
  { key: "ME", name: "Montenegro", countryCode: "ME" },
  { key: "MS", name: "Montserrat", countryCode: "MS" },
  { key: "MA", name: "Morocco", countryCode: "MA" },
  { key: "MZ", name: "Mozambique", countryCode: "MZ" },
  { key: "MM", name: "Myanmar", countryCode: "MM" },
  { key: "NA", name: "Namibia", countryCode: "NA" },
  { key: "NR", name: "Nauru", countryCode: "NR" },
  { key: "NP", name: "Nepal", countryCode: "NP" },
  { key: "NL", name: "Netherlands", countryCode: "NL" },
  { key: "NC", name: "New Caledonia", countryCode: "NC" },
  { key: "NZ", name: "New Zealand", countryCode: "NZ" },
  { key: "NI", name: "Nicaragua", countryCode: "NI" },
  { key: "NE", name: "Niger", countryCode: "NE" },
  { key: "NG", name: "Nigeria", countryCode: "NG" },
  { key: "NU", name: "Niue", countryCode: "NU" },
  { key: "NF", name: "Norfolk Island", countryCode: "NF" },
  { key: "MK", name: "North Macedonia", countryCode: "MK" },
  { key: "MP", name: "Northern Mariana Islands", countryCode: "MP" },
  { key: "NO", name: "Norway", countryCode: "NO" },
  { key: "OM", name: "Oman", countryCode: "OM" },
  { key: "PK", name: "Pakistan", countryCode: "PK" },
  { key: "PW", name: "Palau", countryCode: "PW" },
  { key: "PS", name: "Palestine", countryCode: "PS" },
  { key: "PA", name: "Panama", countryCode: "PA" },
  { key: "PG", name: "Papua New Guinea", countryCode: "PG" },
  { key: "PY", name: "Paraguay", countryCode: "PY" },
  { key: "PE", name: "Peru", countryCode: "PE" },
  { key: "PH", name: "Philippines", countryCode: "PH" },
  { key: "PN", name: "Pitcairn", countryCode: "PN" },
  { key: "PL", name: "Poland", countryCode: "PL" },
  { key: "PT", name: "Portugal", countryCode: "PT" },
  { key: "PR", name: "Puerto Rico", countryCode: "PR" },
  { key: "QA", name: "Qatar", countryCode: "QA" },
  { key: "RE", name: "Réunion", countryCode: "RE" },
  { key: "RO", name: "Romania", countryCode: "RO" },
  { key: "RU", name: "Russia", countryCode: "RU" },
  { key: "RW", name: "Rwanda", countryCode: "RW" },
  { key: "BL", name: "Saint Barthélemy", countryCode: "BL" },
  { key: "SH", name: "Saint Helena", countryCode: "SH" },
  { key: "KN", name: "Saint Kitts and Nevis", countryCode: "KN" },
  { key: "LC", name: "Saint Lucia", countryCode: "LC" },
  { key: "MF", name: "Saint Martin", countryCode: "MF" },
  { key: "PM", name: "Saint Pierre and Miquelon", countryCode: "PM" },
  { key: "VC", name: "Saint Vincent and the Grenadines", countryCode: "VC" },
  { key: "WS", name: "Samoa", countryCode: "WS" },
  { key: "SM", name: "San Marino", countryCode: "SM" },
  { key: "ST", name: "Sao Tome and Principe", countryCode: "ST" },
  { key: "SA", name: "Saudi Arabia", countryCode: "SA" },
  { key: "SN", name: "Senegal", countryCode: "SN" },
  { key: "RS", name: "Serbia", countryCode: "RS" },
  { key: "SC", name: "Seychelles", countryCode: "SC" },
  { key: "SL", name: "Sierra Leone", countryCode: "SL" },
  { key: "SG", name: "Singapore", countryCode: "SG" },
  { key: "SX", name: "Sint Maarten", countryCode: "SX" },
  { key: "SK", name: "Slovakia", countryCode: "SK" },
  { key: "SI", name: "Slovenia", countryCode: "SI" },
  { key: "SB", name: "Solomon Islands", countryCode: "SB" },
  { key: "SO", name: "Somalia", countryCode: "SO" },
  { key: "ZA", name: "South Africa", countryCode: "ZA" },
  { key: "GS", name: "South Georgia", countryCode: "GS" },
  { key: "SS", name: "South Sudan", countryCode: "SS" },
  { key: "ES", name: "Spain", countryCode: "ES" },
  { key: "LK", name: "Sri Lanka", countryCode: "LK" },
  { key: "SD", name: "Sudan", countryCode: "SD" },
  { key: "SR", name: "Suriname", countryCode: "SR" },
  { key: "SJ", name: "Svalbard and Jan Mayen", countryCode: "SJ" },
  { key: "SE", name: "Sweden", countryCode: "SE" },
  { key: "CH", name: "Switzerland", countryCode: "CH" },
  { key: "SY", name: "Syria", countryCode: "SY" },
  { key: "TW", name: "Taiwan", countryCode: "TW" },
  { key: "TJ", name: "Tajikistan", countryCode: "TJ" },
  { key: "TZ", name: "Tanzania", countryCode: "TZ" },
  { key: "TH", name: "Thailand", countryCode: "TH" },
  { key: "TL", name: "Timor-Leste", countryCode: "TL" },
  { key: "TG", name: "Togo", countryCode: "TG" },
  { key: "TK", name: "Tokelau", countryCode: "TK" },
  { key: "TO", name: "Tonga", countryCode: "TO" },
  { key: "TT", name: "Trinidad and Tobago", countryCode: "TT" },
  { key: "TN", name: "Tunisia", countryCode: "TN" },
  { key: "TR", name: "Turkey", countryCode: "TR" },
  { key: "TM", name: "Turkmenistan", countryCode: "TM" },
  { key: "TC", name: "Turks and Caicos Islands", countryCode: "TC" },
  { key: "TV", name: "Tuvalu", countryCode: "TV" },
  { key: "UG", name: "Uganda", countryCode: "UG" },
  { key: "UA", name: "Ukraine", countryCode: "UA" },
  { key: "AE", name: "United Arab Emirates", countryCode: "AE" },
  { key: "GB", name: "United Kingdom", countryCode: "GB" },
  { key: "US", name: "United States", countryCode: "US" },
  {
    key: "UM",
    name: "United States Minor Outlying Islands",
    countryCode: "UM",
  },
  { key: "UY", name: "Uruguay", countryCode: "UY" },
  { key: "UZ", name: "Uzbekistan", countryCode: "UZ" },
  { key: "VU", name: "Vanuatu", countryCode: "VU" },
  { key: "VE", name: "Venezuela", countryCode: "VE" },
  { key: "VN", name: "Vietnam", countryCode: "VN" },
  { key: "VG", name: "Virgin Islands (British)", countryCode: "VG" },
  { key: "VI", name: "Virgin Islands (U.S.)", countryCode: "VI" },
  { key: "WF", name: "Wallis and Futuna", countryCode: "WF" },
  { key: "EH", name: "Western Sahara", countryCode: "EH" },
  { key: "YE", name: "Yemen", countryCode: "YE" },
  { key: "ZM", name: "Zambia", countryCode: "ZM" },
  { key: "ZW", name: "Zimbabwe", countryCode: "ZW" },
] as const;

export type CountryCode = (typeof COUNTRIES)[number]["key"];

/**
 * Array of valid ISO 3166-1 alpha-2 country codes for validation
 */
export const VALID_COUNTRY_CODES = COUNTRIES.map((c) => c.key);

/**
 * Get countries filtered by search term
 */
export function getCountriesFiltered(
  search?: string,
  limit = 1000,
): (typeof COUNTRIES)[number][] {
  let filtered = [...COUNTRIES];

  if (search) {
    const searchLower = search.toLowerCase();
    filtered = filtered.filter(
      (c) =>
        c.name.toLowerCase().includes(searchLower) ||
        c.countryCode.toLowerCase().includes(searchLower),
    );
  }

  return filtered.slice(0, limit);
}
