/**
 * Complete list of languages with ISO 639-1 codes
 * Used for keyword mining and other features requiring standard language codes
 */
export const ISO_LANGUAGES = [
  { value: "aa", label: "Afar" },
  { value: "ab", label: "Abkhazian" },
  { value: "ae", label: "Avestan" },
  { value: "af", label: "Afrikaans" },
  { value: "ak", label: "Akan" },
  { value: "am", label: "Amharic" },
  { value: "an", label: "Aragonese" },
  { value: "ar", label: "Arabic" },
  { value: "as", label: "Assamese" },
  { value: "av", label: "Avaric" },
  { value: "ay", label: "Aymara" },
  { value: "az", label: "Azerbaijani" },
  { value: "ba", label: "Bashkir" },
  { value: "be", label: "Belarusian" },
  { value: "bg", label: "Bulgarian" },
  { value: "bi", label: "Bislama" },
  { value: "bm", label: "Bambara" },
  { value: "bn", label: "Bengali" },
  { value: "bo", label: "Tibetan" },
  { value: "br", label: "Breton" },
  { value: "bs", label: "Bosnian" },
  { value: "ca", label: "Catalan" },
  { value: "ce", label: "Chechen" },
  { value: "ch", label: "Chamorro" },
  { value: "co", label: "Corsican" },
  { value: "cr", label: "Cree" },
  { value: "cs", label: "Czech" },
  { value: "cu", label: "Church Slavonic" },
  { value: "cv", label: "Chuvash" },
  { value: "cy", label: "Welsh" },
  { value: "da", label: "Danish" },
  { value: "de", label: "German" },
  { value: "dv", label: "Divehi" },
  { value: "dz", label: "Dzongkha" },
  { value: "ee", label: "Ewe" },
  { value: "el", label: "Greek" },
  { value: "en", label: "English" },
  { value: "eo", label: "Esperanto" },
  { value: "es", label: "Spanish" },
  { value: "et", label: "Estonian" },
  { value: "eu", label: "Basque" },
  { value: "fa", label: "Persian" },
  { value: "ff", label: "Fula" },
  { value: "fi", label: "Finnish" },
  { value: "fj", label: "Fijian" },
  { value: "fo", label: "Faroese" },
  { value: "fr", label: "French" },
  { value: "fy", label: "Western Frisian" },
  { value: "ga", label: "Irish" },
  { value: "gd", label: "Scottish Gaelic" },
  { value: "gl", label: "Galician" },
  { value: "gn", label: "Guarani" },
  { value: "gu", label: "Gujarati" },
  { value: "gv", label: "Manx" },
  { value: "ha", label: "Hausa" },
  { value: "he", label: "Hebrew" },
  { value: "hi", label: "Hindi" },
  { value: "ho", label: "Hiri Motu" },
  { value: "hr", label: "Croatian" },
  { value: "ht", label: "Haitian" },
  { value: "hu", label: "Hungarian" },
  { value: "hy", label: "Armenian" },
  { value: "hz", label: "Herero" },
  { value: "ia", label: "Interlingua" },
  { value: "id", label: "Indonesian" },
  { value: "ie", label: "Interlingue" },
  { value: "ig", label: "Igbo" },
  { value: "ii", label: "Sichuan Yi" },
  { value: "ik", label: "Inupiaq" },
  { value: "io", label: "Ido" },
  { value: "is", label: "Icelandic" },
  { value: "it", label: "Italian" },
  { value: "iu", label: "Inuktitut" },
  { value: "ja", label: "Japanese" },
  { value: "jv", label: "Javanese" },
  { value: "ka", label: "Georgian" },
  { value: "kg", label: "Kongo" },
  { value: "ki", label: "Kikuyu" },
  { value: "kj", label: "Kuanyama" },
  { value: "kk", label: "Kazakh" },
  { value: "kl", label: "Kalaallisut" },
  { value: "km", label: "Khmer" },
  { value: "kn", label: "Kannada" },
  { value: "ko", label: "Korean" },
  { value: "kr", label: "Kanuri" },
  { value: "ks", label: "Kashmiri" },
  { value: "ku", label: "Kurdish" },
  { value: "kv", label: "Komi" },
  { value: "kw", label: "Cornish" },
  { value: "ky", label: "Kyrgyz" },
  { value: "la", label: "Latin" },
  { value: "lb", label: "Luxembourgish" },
  { value: "lg", label: "Luganda" },
  { value: "li", label: "Limburgish" },
  { value: "ln", label: "Lingala" },
  { value: "lo", label: "Lao" },
  { value: "lt", label: "Lithuanian" },
  { value: "lu", label: "Luba-Katanga" },
  { value: "lv", label: "Latvian" },
  { value: "mg", label: "Malagasy" },
  { value: "mh", label: "Marshallese" },
  { value: "mi", label: "Maori" },
  { value: "mk", label: "Macedonian" },
  { value: "ml", label: "Malayalam" },
  { value: "mn", label: "Mongolian" },
  { value: "mr", label: "Marathi" },
  { value: "ms", label: "Malay" },
  { value: "mt", label: "Maltese" },
  { value: "my", label: "Burmese" },
  { value: "na", label: "Nauru" },
  { value: "nb", label: "Norwegian Bokmål" },
  { value: "nd", label: "North Ndebele" },
  { value: "ne", label: "Nepali" },
  { value: "ng", label: "Ndonga" },
  { value: "nl", label: "Dutch" },
  { value: "nn", label: "Norwegian Nynorsk" },
  { value: "no", label: "Norwegian" },
  { value: "nr", label: "South Ndebele" },
  { value: "nv", label: "Navajo" },
  { value: "ny", label: "Chichewa" },
  { value: "oc", label: "Occitan" },
  { value: "oj", label: "Ojibwe" },
  { value: "om", label: "Oromo" },
  { value: "or", label: "Odia" },
  { value: "os", label: "Ossetian" },
  { value: "pa", label: "Punjabi" },
  { value: "pi", label: "Pali" },
  { value: "pl", label: "Polish" },
  { value: "ps", label: "Pashto" },
  { value: "pt", label: "Portuguese" },
  { value: "qu", label: "Quechua" },
  { value: "rm", label: "Romansh" },
  { value: "rn", label: "Rundi" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "rw", label: "Kinyarwanda" },
  { value: "sa", label: "Sanskrit" },
  { value: "sc", label: "Sardinian" },
  { value: "sd", label: "Sindhi" },
  { value: "se", label: "Northern Sami" },
  { value: "sg", label: "Sango" },
  { value: "si", label: "Sinhala" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "sm", label: "Samoan" },
  { value: "sn", label: "Shona" },
  { value: "so", label: "Somali" },
  { value: "sq", label: "Albanian" },
  { value: "sr", label: "Serbian" },
  { value: "ss", label: "Swati" },
  { value: "st", label: "Southern Sotho" },
  { value: "su", label: "Sundanese" },
  { value: "sv", label: "Swedish" },
  { value: "sw", label: "Swahili" },
  { value: "ta", label: "Tamil" },
  { value: "te", label: "Telugu" },
  { value: "tg", label: "Tajik" },
  { value: "th", label: "Thai" },
  { value: "ti", label: "Tigrinya" },
  { value: "tk", label: "Turkmen" },
  { value: "tl", label: "Tagalog" },
  { value: "tn", label: "Tswana" },
  { value: "to", label: "Tongan" },
  { value: "tr", label: "Turkish" },
  { value: "ts", label: "Tsonga" },
  { value: "tt", label: "Tatar" },
  { value: "tw", label: "Twi" },
  { value: "ty", label: "Tahitian" },
  { value: "ug", label: "Uyghur" },
  { value: "uk", label: "Ukrainian" },
  { value: "ur", label: "Urdu" },
  { value: "uz", label: "Uzbek" },
  { value: "ve", label: "Venda" },
  { value: "vi", label: "Vietnamese" },
  { value: "vo", label: "Volapük" },
  { value: "wa", label: "Walloon" },
  { value: "wo", label: "Wolof" },
  { value: "xh", label: "Xhosa" },
  { value: "yi", label: "Yiddish" },
  { value: "yo", label: "Yoruba" },
  { value: "za", label: "Zhuang" },
  { value: "zh", label: "Chinese" },
  { value: "zu", label: "Zulu" },
] as const;

export type ISOLanguageCode = (typeof ISO_LANGUAGES)[number]["value"];

/**
 * Array of valid ISO 639-1 language codes for validation
 */
export const VALID_LANGUAGE_CODES = ISO_LANGUAGES.map((l) => l.value);

/**
 * Complete list of Meta Ads supported languages
 *
 * Note: Meta uses numeric keys for languages, not ISO codes.
 * This list includes all languages supported by Meta Ads targeting.
 * Source: Meta Marketing API adlocale search
 */
export const META_LANGUAGES = [
  { key: "1", name: "Chinese (Simplified)" },
  { key: "2", name: "Chinese (Traditional)" },
  { key: "3", name: "Chinese (All)" },
  { key: "4", name: "German" },
  { key: "5", name: "Greek" },
  { key: "6", name: "Portuguese" },
  { key: "7", name: "Spanish" },
  { key: "8", name: "Swedish" },
  { key: "9", name: "Turkish" },
  { key: "10", name: "French" },
  { key: "11", name: "Hebrew" },
  { key: "12", name: "Hindi" },
  { key: "13", name: "Czech" },
  { key: "14", name: "Danish" },
  { key: "15", name: "Indonesian" },
  { key: "16", name: "Italian" },
  { key: "17", name: "Hungarian" },
  { key: "18", name: "Japanese" },
  { key: "19", name: "Arabic" },
  { key: "20", name: "Korean" },
  { key: "21", name: "Malay" },
  { key: "22", name: "Norwegian (bokmal)" },
  { key: "23", name: "Polish" },
  { key: "24", name: "English (US)" },
  { key: "25", name: "English (UK)" },
  { key: "26", name: "Romanian" },
  { key: "27", name: "Slovak" },
  { key: "28", name: "Dutch" },
  { key: "29", name: "Bulgarian" },
  { key: "30", name: "Catalan" },
  { key: "31", name: "Finnish" },
  { key: "32", name: "Afrikaans" },
  { key: "33", name: "Russian" },
  { key: "34", name: "Slovenian" },
  { key: "35", name: "Thai" },
  { key: "36", name: "Ukrainian" },
  { key: "37", name: "Vietnamese" },
  { key: "38", name: "Serbian" },
  { key: "39", name: "Croatian" },
  { key: "40", name: "Bengali" },
  { key: "41", name: "Cebuano" },
  { key: "42", name: "Estonian" },
  { key: "43", name: "Filipino" },
  { key: "44", name: "Galician" },
  { key: "45", name: "Gujarati" },
  { key: "46", name: "Kannada" },
  { key: "47", name: "Latvian" },
  { key: "48", name: "Lithuanian" },
  { key: "49", name: "Malayalam" },
  { key: "50", name: "Marathi" },
  { key: "51", name: "Nepali" },
  { key: "52", name: "Punjabi" },
  { key: "53", name: "Tamil" },
  { key: "54", name: "Telugu" },
  { key: "55", name: "Urdu" },
  { key: "56", name: "Swahili" },
  { key: "57", name: "Zulu" },
  { key: "58", name: "Welsh" },
  { key: "59", name: "Basque" },
  { key: "60", name: "Icelandic" },
  { key: "61", name: "Irish" },
  { key: "62", name: "Maltese" },
  { key: "63", name: "Bosnian" },
  { key: "64", name: "Albanian" },
  { key: "65", name: "Macedonian" },
  { key: "66", name: "Azerbaijani" },
  { key: "67", name: "Georgian" },
  { key: "68", name: "Kazakh" },
  { key: "69", name: "Armenian" },
  { key: "70", name: "Khmer" },
  { key: "71", name: "Lao" },
  { key: "72", name: "Burmese" },
  { key: "73", name: "Mongolian" },
  { key: "74", name: "Sinhala" },
  { key: "75", name: "Amharic" },
  { key: "76", name: "Hausa" },
  { key: "77", name: "Igbo" },
  { key: "78", name: "Yoruba" },
  { key: "79", name: "Javanese" },
  { key: "80", name: "Sundanese" },
  { key: "81", name: "Oriya" },
  { key: "82", name: "Assamese" },
  { key: "83", name: "Somali" },
  { key: "84", name: "Tigrinya" },
  { key: "85", name: "Frisian" },
  { key: "86", name: "Luxembourgish" },
  { key: "87", name: "Scots Gaelic" },
  { key: "88", name: "Kyrgyz" },
  { key: "89", name: "Tajik" },
  { key: "90", name: "Turkmen" },
  { key: "91", name: "Uzbek" },
  { key: "92", name: "Pashto" },
  { key: "93", name: "Kurdish" },
  { key: "94", name: "Persian" },
  { key: "95", name: "English (All)" },
  { key: "96", name: "Spanish (Spain)" },
  { key: "97", name: "Portuguese (Portugal)" },
  { key: "98", name: "Portuguese (Brazil)" },
  { key: "99", name: "French (France)" },
  { key: "100", name: "French (Canada)" },
  { key: "101", name: "Spanish (Latin America)" },
] as const;

export type MetaLanguageKey = (typeof META_LANGUAGES)[number]["key"];

/**
 * Get languages filtered by search term
 */
export function getLanguagesFiltered(
  search?: string,
  limit = 1000,
): (typeof META_LANGUAGES)[number][] {
  let filtered = [...META_LANGUAGES];

  if (search) {
    const searchLower = search.toLowerCase();
    filtered = filtered.filter((l) =>
      l.name.toLowerCase().includes(searchLower),
    );
  }

  return filtered.slice(0, limit);
}
